"""Study-path and study-plan agent.

Turns a goal (e.g. target roles), the user's current skills, weekly available
hours and a deadline into:
  - a learning path (ordered topics with reasons and resources)
  - a weekly plan (week by week focus / hours / deliverable)
  - milestones and quick wins

Everything is generated by an LLM and returned as structured JSON.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent.llm import LLM  # noqa: E402


PLANNER_SYSTEM = (
    "You are a study-planning coach for someone preparing for technical job "
    "interviews. Given the user's goal, current skills, target roles, weekly "
    "study hours and deadline, build a practical learning plan.\n"
    "Rules:\n"
    "- Order topics by impact on the target roles; put quick wins first.\n"
    "- Every topic needs a concrete reason and at least one real resource "
    "(official docs, book, or course name).\n"
    "- Weekly plan must respect the given hours budget; split into coding "
    "practice, theory and project work.\n"
    "- Do NOT invent the user's current skill level; use only what is given.\n"
    "- Return ONLY JSON, no markdown fences:\n"
    '{"path": [{"topic": "...", "reason": "...", "resources": ["..."]}],\n'
    ' "weekly_plan": [{"week": 1, "focus": "...", "hours": 12, '
    '"deliverable": "..."}],\n'
    ' "milestones": ["..."], "quick_wins": ["..."]}'
)


def plan_study(
    goal: str,
    current_skills: str = "",
    target_roles: str = "",
    hours_per_week: int = 15,
    deadline: str = "",
    notes: str = "",
) -> dict:
    """Generate a study path and weekly plan. Returns the parsed JSON dict."""
    prompt = (
        f"求职/学习目标：{goal}\n"
        f"当前技能：{current_skills or '（未提供）'}\n"
        f"目标岗位方向：{target_roles or '（未提供）'}\n"
        f"每周可用学习时间：{hours_per_week} 小时\n"
        f"截止时间：{deadline or '（未提供）'}\n"
        f"补充说明：{notes or '（无）'}\n"
    )
    llm = LLM()
    out = llm.chat_json(PLANNER_SYSTEM, prompt)
    return out.get("data") or {}
